blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='index'),
]

books/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('books/', views.BookList.as_view(), name='books'),
    path('create/', views.BookCreate.as_view(), name='create_book'),
    path('delete/<slug:slug>', views.BookDelete.as_view(), name='book_delete'),
    path('edit/<slug:pk>/', views.BookEdit.as_view(), name='book_edit'),
    path('<slug:slug>/', views.BookDetail.as_view(), name='books_detail'),
    path('like/<slug:slug>', views.BookLike.as_view(), name='book_like'),
    
    ]

librumamatis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls'), name='blog_urls'),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('books/', include('books.urls'), name='books_urls'),
    path('accounts/', include('allauth.urls')),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from cloudinary.models import CloudinaryField


class Book(models.Model):
    """A model to create Book items"""
    book_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, null=False, unique=True)
    writer = models.CharField(max_length=200, unique=True,)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_books"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    review = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User, related_name='books_like', blank=True)

    def __str__(self):
        return self.book_title

    def get_absolute_url(self):
        return reverse("books_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.book_title)
        return super().save(*args, **kwargs)

    class Meta:
        """Created on order"""
        ordering = ["-created_on"]

    def __str__(self):
        return self.book_title

    def number_of_likes(self):
        """Books likes"""
        return self.likes.count()


class Review(models.Model):
    """ A model to make a review """
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """ Order by created on date """
        ordering = ["created_on"]

    def __str__(self):
        return f"Review {self.body} by {self.name}"

books/forms.py
from .models import Review, Book
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('body',)


class BookForm(forms.ModelForm):
    """ A form to create a Book"""
    class Meta:
        model = Book
        fields = (
            'book_title',
            'writer',
            'featured_image',
            'review',
        )
        widgets = {
            'review': SummernoteWidget()
        }

blog/views.py
from django.shortcuts import render
from django.views import generic


def index(request):
    """ Return homepage """
    return render(request, 'index.html')

books/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView, DetailView, CreateView, DeleteView, UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Book
from .forms import ReviewForm, BookForm


class BookList(ListView):
    model = Book
    queryset = Book.objects.order_by("-created_on")
    template_name = "books.html"
    paginate_by = 6


class BookDetail(DetailView):

    def get(self, request, slug, *args, **kwargs):
        queryset = Book.objects
        book = get_object_or_404(queryset, slug=slug)
        reviews = book.reviews.order_by("-created_on")
        liked = False
        if book.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "books_detail.html",
            {
                "book": book,
                "reviews": reviews,
                "liked": liked,
                "review_form": ReviewForm()
            }
        
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Book.objects
        book = get_object_or_404(queryset, slug=slug)
        reviews = book.reviews.order_by("-created_on")
        liked = False
        if book.likes.filter(id=self.request.user.id).exists():
            liked = True

        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review_form.instance.email = request.user.email
            review_form.instance.name = request.user.username
            review = review_form.save(commit=False)
            review.book = book
            review.save()
        else:
            review_form = ReviewForm()

        return render(
            request,
            "books_detail.html",
            {
                "book": book,
                "reviews": reviews,
                "reviewed": True,
                "liked": liked,
                "review_form": ReviewForm()
            }
        
        )


class BookLike(CreateView):
    """ A view to like a book """

    def post(self, request, slug):
        """ A function to add or remove a like """
        book = get_object_or_404(Book, slug=slug)

        if book.likes.filter(id=request.user.id).exists():
            book.likes.remove(request.user)
        else:
            book.likes.add(request.user)

        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class BookCreate(CreateView):
    """ A view to create a book """

    form_class = BookForm
    template_name = 'create_book.html'
    success_url = "/books/books/"
    model = Book

    def form_valid(self, form):
        """ If form is valid return to Add a book """
        form.instance.author = self.request.user
        messages.success(self.request, 'Book posted successfully')
        return super(BookCreate, self).form_valid(form)


class BookDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ A view to delete a book """
    model = Book
    template_name = 'book_delete.html'
    success_url = "/books/books/"

    def test_func(self):
        return self.request.user == self.get_object().author


class BookEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ A view to edit a book """

    Model = Book
    form_class = BookForm
    success_url = "/books/books/"
    template_name = "book_edit.html"
    queryset = Book.objects

    def form_valid(self, form):
        """ If form is valid return Book page"""
        self.success_url + str(self.object.pk) + '/'
        messages.success(self.request, 'Book updated successfully')
        return super().form_valid(form)

    def test_func(self):
        """ A function to test if the user is the author """
        return self.request.user == self.get_object().author

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="book, to read, suggest book, book blog">
    <meta name="description" content="Librum Amatis, a blog to share reviews on books.">
    <!-- bootstrap css link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- bootstrap js link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <!-- my css link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- font awesome link -->
    <script src="https://kit.fontawesome.com/aad6cd9071.js" crossorigin="anonymous"></script>
    <title>Librum Amatis</title>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <!--Title -->
        <a class="navbar-brand" href="{% url 'index' %}">Librum Amatis</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation list -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav text-end">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books' %}">Books</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_book' %}">Add a Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- allert messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>


    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <p class="m-0 text-center">Librum Amatis</p>
        <p class="m-0 text-center">Contact us at: librumamatis@google.com</p>
        <p class="m-0 text-center">Follow us:
            <!-- Facebook link-->
            <a class="social-links" href="https://www.facebook.com" target="_blank" rel="noopener"
                aria-label="Please visit our Facebook Page (opens in a new tab)">
                <i class="fab fa-facebook-square ms-3"></i></a>
            <!-- Twitter link -->
            <a class="social-links" href="https://twitter.com" target="_blank" rel="noopener"
                aria-label="Please visit our Twitter Page (opens in a new tab)">
                <i class="fab fa-twitter-square ms-3"></i></a>
            <!-- Instagram link -->
            <a class="social-links" href="https://www.instagram.com/" target="_blank" rel="noopener"
                aria-label="Please visit our Instagram Page (opens in a new tab)">
                <i class="fab fa-instagram-square ms-3"></i></a>
            <!-- Youtube link -->
            <a class="social-links" href="https://youtube.com/" target="_blank" rel="noopener"
                aria-label="Please visit our Youtube Page (opens in a new tab)">
                <i class="fab fa-youtube-square ms-3"></i></a>
        </p>
    </footer>
    <script>
        setTimeout(function(){
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>


</body>

</html>

templates/book_delete.html
{% extends "base.html" %}



{% block content %}


<div class="row col-md-8 offset-md-2 delete-book">
    <div class="col-md-8 offset-md-2 p-3">
        <!-- Delete Book heading -->
        <h1 class="text-center">Delete the Book</h1>
        <div class="d-flex justify-content-center pt-3">
            <!-- Delete Book confirmation form-->
            <form method="post" class="text-center p-5">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ book.book_title }}"?</p>
                <input type="submit" value="Confirm" class="btn btn-outline-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/book_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <!-- Edit a Book form heading and information -->
    <h1>Edit your Book</h1>
    <p>If you have any updates or you want to change something to your existing book, please update them here.</p>
    <!-- Edit Book form-->
    <div id="edit-book-form">
    <form class="edit_book_form" action="{% url 'book_edit' book.id %}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.id }}
        {{ form|crispy }}
        {{ form.media }}

        <input class="btn btn-outline-primary" type="submit" value="Submit">
    </form>
   </div>
</div>
{% endblock %}

templates/books.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid">
    <div class="row">
       <!-- Books Column -->
                {% for book in book_list %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                {% if "placeholder" in book.featured_image.url %}
                                <!-- Placeholder image-->
                                <img class="card-img-top book-page-pic" 
                                src="" 
                                alt="">
                                {% else %}
                                <!-- User image -->
                                <img class="card-img-top book-page-pic" src="{{ book.featured_image.url }}" alt="book's cover">
                                {% endif %}
                                <!-- Book Author-->
                                <div>
                                    <p class="image-flash">Author: {{ book.author }}</p>
                                </div>
                                <!--link to book detail page -->
                            <a href="{% url 'books_detail' book.slug %}" class="book-link">
                                <h2 class="card-title">{{ book.book_title }}</h2>
                                <h4 class="card-text">{{ book.writer }}</h4>
                            </a>
                            <hr>
                            <!-- date books was updated on and number of likes -->
                            <p class="card-text h6">{{ book.updated_on}}</p><i
                                    class=" card-text far fa-heart">{{ book.number_of_likes }}</i>   
                            </div>
                        </div>
                    </div>
                <!-- starts a new row after every 3 books posted -->
                {% if forloop.counter|divisibleby:3 %}

            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
    </div>
    <!-- puts next page button at the bottom of the page when there are more than 6 books on a page-->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>


{% endblock %}

templates/books_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}

<!-- Book detail card -->
<div class="masthead">
    <div class="container pic-padding">
        <div class="row">
            <div class="col-md-6 masthead-text">
                <h1 class="book-title">{{ book.book_title }}</h1>
                <h3 class="book-subtitle">{{ book.writer }}</h3>
        <div class="col book-author">
            <div class="col col-author">
                <p class="author">{{ book.author }} | {{ book.created_on }}</p>
            </div>
            <div class="col ">
            <!-- Delete Book -->
                {% if book.author == request.user%}
                <span>
                    <a href="{% url 'book_delete' book.slug %}" class="delete small-icon"
                    aria-label="Click to delete a Book">
                    <i class="far fa-trash-alt fa-1x"></i></a>
                  </span>
            <!-- Edit Book -->
                  <span>
                    <a href="{% url 'book_edit' book.id %}" class="edit small-icon" aria-label="Click to edit book">
                    <i class="far fa-edit fa-1x"></i></a>
                   </span>
                   {% endif %}
            </div>
            </div>
        </div>

            <div class="col-md-6 masthead-image">
                {% if "placeholder" in book.featured_image.url %}
                <img class="border border-light book-detail-pic card-img-top">
                {% else %}
                <img class="border border-light book-detail-pic" src=" {{ book.featured_image.url }}" alt="book's cover">
                {% endif %}

            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left top">
            <div class="card-body">
                <p class="card-text ">
                    {{ book.review | safe }}</p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'book_like' book.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="bookpost_id" value="{{book.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="bookpost_id" value="{{book.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        
                        <span class="text-secondary">{{ book.number_of_likes }} </span>
                        </strong>                       
                    </div>
                    <div class="col-1">
                        {% with reviews.count as total_reviews %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            {{ total_reviews }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Reviews:</h3>
            <div class="card-body">
                {% for review in reviews %}
                <div class="reviews" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ review.name }}
                        <span class=" card-text font-weight-normal">
                            {{ review.created_on }}
                        </span> wrote:
                    </p>
                    {{ review.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if user.is_authenticated %}

                <h3>Leave a review:</h3>
                <p>Posting as: {{ user.username }}</p>
                
                <form method="post" style="margin-top: 1.3em;">
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </form>
                
                {% endif %}
    
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/create_book.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<div class="container">
    <!-- Create form header and information -->
    <h1>Add your favourite Book</h1>
    <p>Do you have a book you felt in Love with?</p>
    <p>Complete the form below and let others know which Book is!</p>
    <!-- Create Book form -->
    <form class="create_book_form" method="POST" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{form | crispy}}
    

        <button type="submit" class="btn btn-outline-primary">Submit</button>






    </form>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid text-center">
    <div class="row">
        </div>
        <h1 class="tag-line">
            Welcome to Librum Amatis!
        </h1>
        <!-- Hero Image-->
        <div class="col-md-10 offset-md-1">
            <img class="img-fluid hero-image border border-light"
                src="https://res.cloudinary.com/dqwmxwpay/image/upload/v1674317409/hero-image_1_ac6les.jpg" 
                alt="An open book">
        </div>
        <div class="col-12">
            <!-- About section -->
            <p>Here on Librum Amatis you can have a look of the books that I love the most with reviews.
                Other users have been doing the same. 
            </p>
            <p>Have a look at our books and let us know what you think about it, and please share with us your favourite
                books. Have fun !
            </p>
    </div>
</div>


{% endblock %}